git_repository(
  name = "remote_protobuf",
  remote = "https://github.com/google/protobuf.git",
  commit = "c9418912cb5483551fecde5463c56a0ae40830fb",
)

bind(
  name = "protoc",
  actual = "@remote_protobuf//:protoc"
)

bind(
  name = "protobuf_clib",
  actual = "@remote_protobuf//:protobuf",
)

bind(
  name = "protobuf",
  actual = "//third_party:protobuf",
)

